### ISSUE TITLE
Test fonctionnel "file does not exist"

### ISSUE THREAD

**Issue by stakovicz** [afup/web#1357]
Lors de l’exécution du test fonctionnel : `tests/behat/features/PublicSite/Register.feature` une erreur "file does not exist" remonte.

Cela provient du Client Google qui n'est pas configuré en environnement de test.

Cela se fait via le paramètre : 

```yaml
# app/config/parameters.yml
parameters:
    google_groups_api_key: ""
```

en spécifiant le chemin du fichier json d'authentification.

Pour reproduire le bug, se mettre dans le container et lancer la commande : 
```
./bin/behat tests/behat/features/PublicSite/Register.feature
```
